# Site settings
title: Corey H. Walsh
email: coreyhwalsh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  L33t Haxor, student, and philosoraptor.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rayban.vision" # the base hostname & protocol for your site
github_username:  kctess5
port: 2000

scripts:
    root: "/js/"
    files:
        - hbs.js
        - templates.js
        - init.min.js

# Meta
type: blog
favicon:
    dir: /favicons/
    version: "0"
    tile_color: "#da532c"
google:
    analytics_id: UA-47443701-4
# Build settings
markdown: kramdown

# Directory Config
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
data_source: ./content/_data
collections: null
exclude: 
    - gulpfile.js
    - package.json
    - README.md
    - server.js
    - node_modules
    - npm-debug.log

defaults:
  -
    scope:
      path: "content" # an empty string here means all files in the project
    values:
      layout: pane
  -
    scope:
      path: content/blog # an empty string here means all files in the project
    values:
      layout: pane
      comments: true
  -
    scope:
      path: content/classes # an empty string here means all files in the project
    values:
      layout: pane
  -
    scope:
      path: content/ideas # an empty string here means all files in the project
    values:
      layout: pane
      comments: true
